version: '2'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/mnt/shared/code/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=xabitelle
      - INFLUXDB_ADMIN_PASSWORD= MFONWOOCLCNRO
volumes:
  influxdb-storage: